name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build the project
      - name: Build
        run: npm run build --if-present

      # Run tests
      - name: Run tests
        run: npm test

      # Run coverage
      - name: Generate coverage
        run: npm run coverage

      # Upload test results
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.node-version }}-${{ github.run_id }}
          path: |
            coverage/lcov-report
            coverage/clover.xml
            test-report.html


      # Optionally: print coverage summary in logs
      - name: Print coverage summary
        run: npx nyc report --reporter=text-summary
